DROP INDEX IF EXISTS index_posts_user_id;
DROP INDEX IF EXISTS index_comments_user_id;
DROP INDEX IF EXISTS index_subreddit_user_id;
DROP INDEX IF EXISTS index_votes_user_id;
DROP INDEX IF EXISTS index_votes_comments_user_id;
DROP INDEX IF EXISTS index_subreddits_admin_id;
DROP INDEX IF EXISTS index_posts_subreddit_id;
DROP INDEX IF EXISTS index_posts_subreddit_created_at_desc;
DROP INDEX IF EXISTS index_votes_post_id_vote_type;